### ISSUE TITLE
Keyrings Error

### ISSUE THREAD

**Issue by aefruswg** [CrowdStrike/Falcon-Toolkit#150]
Getting the following error when trying to create a new profile in a fresh Ubuntu instance in WSL2. This comes up after entering my client ID and secret. Keyring and Keyrings.alt are installed. Please help. I just want a bulk maintenance token and searching for how to find it in the admin console led me here.

> Traceback (most recent call last):
  File "/home/ME/.local/bin/falcon", line 8, in <module>
    sys.exit(cli())
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/falcon.py", line 284, in profiles_new
    config.add_instance()
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/common/config.py", line 176, in add_instance
    new_instance.auth_backend = auth_backend()
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/common/auth_backends/public_single_cid.py", line 46, in __init__
    self.client_secret = fancy_input("Client Secret: ")
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/common/auth_backends/public_single_cid.py", line 73, in client_secret
    keyring.set_password(
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/keyring/core.py", line 61, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/ME/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/keyring/backends/fail.py", line 28, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

**Comment by ChristopherHammond13** [comment]
Hey @aefruswg

`keyring` requires a secure backend to store the API keys in, which is typically FreeDesktop Secret Service on Linux. Once that's configured, `keyring` should pick it up automatically.

But, to solve your main problem, the bulk maintenance token is available in Sensor Update Policies within the Falcon Console.

Let us know how you get on!

**Comment by aefruswg** [comment]
Resolved by getting bulk token from sensor updates. I promise you I looked for where to find it and was not directed there

**Comment by ChristopherHammond13** [comment]
Thanks so much for following up, @aefruswg! If you require any further support with the Toolkit feel free to open a new issue, otherwise if we at CrowdStrike can assist at all with anything else please do not hesitate to open a ticket with our wonderful support team.
