### ISSUE TITLE
Unable to run command in RTR

### ISSUE THREAD

**Issue by vietde** [CrowdStrike/Falcon-Toolkit#33]
Hi,
I test a update list command on Windows side but giving me this error. Hopefully we can get it fix next update. I think this is a nice tool to have. Thank you 
`C:\> update list
Executing command: update list
Traceback (most recent call last):
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/cmd2/cmd2.py", line 2399, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/cmd2/cmd2.py", line 2852, in onecmd
    stop = func(statement)
           ^^^^^^^^^^^^^^^
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/cmd2/decorators.py", line 382, in cmd_wrapper
    return func(*args_list, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/falcon_toolkit/shell/prompt.py", line 1035, in do_update
    self.send_generic_command(command)
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/falcon_toolkit/shell/prompt.py", line 428, in send_generic_command
    batch_results = self.batch_session.run_generic_command(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/caracara/modules/rtr/batch_session.py", line 35, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ /.local/pipx/venvs/falcon-toolkit/lib/python3.11/site-packages/caracara/modules/rtr/batch_session.py", line 412, in run_generic_command
    all_responses.update(complete['combined']['resources'])
                         ~~~~~~~~^^^^^^^^^^^^
KeyError: 'combined'`

**Comment by ChristopherHammond13** [comment]
Closing due to lack of activity, but will reopen if there are further issues
