### ISSUE TITLE
RTR shell errors out when specifying AID

### ISSUE THREAD

**Issue by lautriv** [CrowdStrike/Falcon-Toolkit#65]
Using `package falcon-toolkit 3.2.0, installed using Python 3.9.13` I'm having issues connecting to systems with RTR by specifying AID.

```
PS C:\Users\ibarton> falcon -p ...snip... shell -d ...snip...
Falcon Toolkit
Configuration Directory: C:\Users\ibarton\AppData\Local\CrowdStrike\FalconToolkit
Connecting to the device IDs provided on the command line
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
    exec(code, run_globals)
  File "c:\users\ibarton\.local\bin\falcon.exe\__main__.py", line 7, in <module>
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\ibarton\.local\pipx\venvs\falcon-toolkit\lib\site-packages\falcon_toolkit\shell\cli.py", line 158, in cli_shell
    device_ids = client.hosts.filter_by_online_state(
AttributeError: 'HostsApiModule' object has no attribute 'filter_by_online_state'
```

Oddly enough I was able to connect to the same system when specifying a Hostname filter, so it appears to be limited to the AID logic.

**Comment by ChristopherHammond13** [comment]
I strongly suspect this is due to some online state filtering code that was only half stripped out. @kenoel tagging you for awareness here, as there may be some lingering expectations of that filter's existence.

**Comment by kenoel** [comment]
A function was changed in Caracara and wasn't updated here. This commit should fix the issue.
