### ISSUE TITLE
[{'code': 400, 'message': 'request must contain between 0 and 100 ids'}]

### ISSUE THREAD

**Issue by MuhammadChang** [CrowdStrike/Falcon-Toolkit#77]
crowd@crowd-VirtualBox:~$ falcon host_search -f OS=Windows
Falcon Toolkit
Configuration Directory: /home/crowd/.local/share/FalconToolkit
Searching for hosts...
Traceback (most recent call last):
  File "/home/crowd/.local/bin/falcon", line 8, in <module>
    sys.exit(cli())
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/hosts/cli.py", line 53, in cli_host_search
    host_search_cmd(client, filters, online_state)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/falcon_toolkit/hosts/host_search.py", line 29, in host_search_cmd
    host_data = client.hosts.describe_devices(filters=fql, online_state=online_state)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/caracara/filters/decorators.py", line 56, in wrapper
    return func(*_args.args, **_args.kwargs)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/caracara/modules/hosts/hosts.py", line 153, in describe_devices
    device_state_data = self.get_online_state(device_ids)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/caracara/modules/hosts/_online_state.py", line 59, in get_online_state
    device_online_state_data = batch_get_data(device_ids, self.hosts_api.get_online_state)
  File "/home/crowd/.local/pipx/venvs/falcon-toolkit/lib/python3.10/site-packages/caracara/common/batching.py", line 117, in batch_get_data
    raise Exception("At least one thread returned an error: " + str(errors))
Exception: At least one thread returned an error: [{'code': 400, 'message': 'request must contain between 0 and 100 ids'}]

**Comment by ChristopherHammond13** [comment]
Hi there, thank you for raising this! This bug should be fixed by upgrading Falcon Toolkit to the latest version (`pipx upgrade Falcon-Toolkit` should do this for you).

If you still get it on the latest release let us know and we'll figure out what's going on here.

CC: @kenoel for awareness

**Comment by MuhammadChang** [comment]
fixed, roll back to an older version

**Comment by ChristopherHammond13** [comment]
I'm glad you got this to work. If you experience the issue on the latest version of the Toolkit (v3.2.1, or higher), please reopen the ticket and we can look into this again.
